train:
  project_name: unitree_go1_antalgic
  task: Template-Go1-Lab-v0
  agent: rsl_rl_phase3_cfg_entry_point

  num_envs: 2048
  max_iterations: 4000 # 8000, 500
  normalize: false
  mse_norm: 
    enable: true

    action_mean: 0.0
    action_pstd: 0.0

    splint_mean: 0.0
    splint_std: 0.0

    vel_mean: 0.0
    vel_pstd: 0.0

  seed: 42

  num_steps_per_env: 50
  gradient_length: 50

  splint_loss_coef: 1.0
  vel_loss_coef: 1.0
  
checkpoint:
  mode: "distill" # warmstart, resume
  # Phase 2 teacher (부목 모델 v2)
  teacher: ""
  student: ""
  load_optimizer: false # false, true
  reset_iteration: true
  reset_noise_std: false    # warmstart 시 init_noise_std 로 std 를 되돌린다


env:
  path: ../../env/antalgic.yaml
 
eval:
  peg_leg: normal # normal, fl, fr, rl, rr

exploration:
  noise_std:
    # 실제 사용할 탐색 노이즈 방식
    set: log  # scalar 또는 log

    types:
      scalar:
        init_noise_std: 1.0
        min_action_std: 0.001

      log:
        init_noise_std: 0.05
        min_action_std: 0.001