# cd /home/robotserver/wj/go1_antalgic/scripts/rsl_rl && nohup /home/robotserver/wj/.venvs/isaaclab-5.1-antalgic/bin/python train.py --phase_config_path configs/phase/1/phase1.yaml --run_tag P1-001 --headless --debug_obs --debug_obs_envs 10 > logs/p1_001.out 2>&1 &

train:
  project_name: unitree_go1_antalgic 
  task: Template-Go1-Lab-v0
  agent: rsl_rl_phase1_cfg_entry_point
  
  num_envs: 2048
  max_iterations: 5000

  normalize: 
    enable: false
    
    obs:
      # mean: [0.01, 0.0, 0.01], std: [0.58, 0.35, 0.25], max: [10.72, 4.26, 2.75], min: [-10.56, -3.82, -2.86]
      angular_vel: 1.0

      # mean: [-0.43, -0.01, -1] std: [0.07, 0.07, 0.05], max: [0.59,	0.62, -0.65], min: [-0.43	-0.72	-1.24]
      gravity: 1.0

      # mean: [0.52, 0.00,	0.01] std: [0.27,	0.17,	0.23], max: [1.00, 0.30, 0.40], min: [0.00, -0.30, -0.40]
      cmd_vel: 1.0

      joint_pos: 1.0

      # mean: -0.05, 0.02, -0.02, 0.01, 0.22, 0.08, -0.11, -0.10, -0.43, -0.15, 0.30, 0.23
      # min: -17.29, -19.39, -19.16, -19.38, -22.18, -21.27, -13.81, -15.90, -20.10, -20.08, -20.09, -20.06
      # max: 18.20, 19.23, 24.47, 19.12, 16.00, 16.90, 17.11, 14.65, 20.10,20.09, 20.08, 20.10
      # std: 
      joint_vel: 0.23
      action: 1.0

    priv:
      splint_length: 1
      linear_vel: 1
  


  seed: 42

  num_steps_per_env: 24

checkpoint:
  mode: scratch
  teacher: 
  student: 
  load_optimizer: false 
  reset_iteration: true

env:
  path: ../../env/healthy.yaml


eval:
  peg_leg: normal 


# 덮어씌우는 부분 기능 수정
exploration:
  noise_std:
    # 실제 사용할 탐색 노이즈 방식
    set: log  # scalar 또는 log

    types:
      scalar:
        init_noise_std: 1.0
        min_action_std: 0.001

      log:
        init_noise_std: 1.0
        min_action_std: 0.001

overrides: {}